concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "995e1ee11e10"
  url = "https://gitlab.com"
  id = 47697721
  token = "glrt-gqIe1sUP0PxkorxO4yTWum86MQpwOjE1bXYzcAp0OjMKdTo4NG92dhg.01.1j0wirv7b"
  token_obtained_at = 2025-06-03T14:04:30Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:dind"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache","/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
    network_mtu = 0
